/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { checkboxListItem, } from "./components/save-dialog/save-dialog";
export namespace Components {
    interface ProductTile {
        "imageSrc": string;
        "lists": string;
        "price": string;
        "pricePerUnit": string;
        "productId": string;
        "productName": string;
    }
    interface SaveDialog {
        "lists": checkboxListItem[];
        "productId": string;
    }
}
declare global {
    interface HTMLProductTileElement extends Components.ProductTile, HTMLStencilElement {
    }
    var HTMLProductTileElement: {
        prototype: HTMLProductTileElement;
        new (): HTMLProductTileElement;
    };
    interface HTMLSaveDialogElement extends Components.SaveDialog, HTMLStencilElement {
    }
    var HTMLSaveDialogElement: {
        prototype: HTMLSaveDialogElement;
        new (): HTMLSaveDialogElement;
    };
    interface HTMLElementTagNameMap {
        "product-tile": HTMLProductTileElement;
        "save-dialog": HTMLSaveDialogElement;
    }
}
declare namespace LocalJSX {
    interface ProductTile {
        "imageSrc"?: string;
        "lists"?: string;
        "onAddList"?: (event: CustomEvent<any>) => void;
        "onToggleSelection"?: (event: CustomEvent<any>) => void;
        "price"?: string;
        "pricePerUnit"?: string;
        "productId"?: string;
        "productName"?: string;
    }
    interface SaveDialog {
        "lists"?: checkboxListItem[];
        "onClose"?: (event: CustomEvent<any>) => void;
        "onCreate"?: (event: CustomEvent<string>) => void;
        "onToggle"?: (event: CustomEvent<number>) => void;
        "productId"?: string;
    }
    interface IntrinsicElements {
        "product-tile": ProductTile;
        "save-dialog": SaveDialog;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "product-tile": LocalJSX.ProductTile & JSXBase.HTMLAttributes<HTMLProductTileElement>;
            "save-dialog": LocalJSX.SaveDialog & JSXBase.HTMLAttributes<HTMLSaveDialogElement>;
        }
    }
}
